version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting Docker Daemon"
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo Entered the build phase...
      - npm install -g serverless@4.4.7
      - serverless plugin install -n serverless-dotenv-plugin 
      - serverless plugin install -n serverless-python-requirements 
      - serverless plugin install -n serverless-plugin-log-retention 
      - serverless plugin install -n serverless-prune-plugin 
      - serverless plugin install -n serverless-step-functions 
      - serverless plugin install -n serverless-plugin-split-stacks
      - serverless plugin install -n serverless-plugin-aws-alerts
      - serverless plugin install -n serverless-plugin-tracing
      - npm install --save-dev serverless-dotenv-plugin
  post_build:
    commands:
      - serverless deploy --stage $environment --verbose --force