  S3toDynamoDBLambdaFunction:
    module: src/s3_to_dynamodb
    handler: handler.main
    runtime: python3.10
    name: s3-to-dynamodb-lambda-function
    role: iamRoleS3toDynamoDBLambdaFunction
    environment:
      REGION: ${env:REGION}
      LOG_LEVEL: ${env:LOG_LEVEL}
      LOG_FORMAT: ${env:LOG_FORMAT}


 