DevopsDaysRule:
  Type: AWS::Events::Rule
  Properties:
    EventPattern:
      source:
        - aws.s3
    Name: devops-days-rule
    State: ENABLED
    Targets:
      - Arn: "arn:aws:lambda:us-east-1:768312754627:function:devops-days-lambda-function"
        Id: devops-days-lambda-function
        RoleArn:
          Fn::GetAtt: [ "iamDevopsDaysLambdaFunctionExecution", "Arn" ]
        RetryPolicy:
          MaximumRetryAttempts: 5
          MaximumEventAgeInSeconds: 60