DevopsDaysRule:
  Type: AWS::Events::Rule
  Properties:
    EventBusName: default
    EventPattern:
      source:
        - aws.s3
    Name: devops-days-rule
    State: ENABLED
    Targets:
      - Arn:
          Fn::GetAtt: [ "DevopsDaysLambdaFunction", "Arn" ]
        Id: devops-days-lambda-function
        RoleArn:
          Fn::GetAtt: [ "iamDevopsDaysLambdaFunctionExecution", "Arn" ]
        RetryPolicy:
          MaximumRetryAttempts: 5
          MaximumEventAgeInSeconds: 60